In [1]:
import numpy as np

# --> Creating **NumPy Array** from **Python List**

In [2]:
# Creating 1D Array

mylist = [1,2,3,4]

In [3]:
type(mylist)

list

In [4]:

np.array(mylist)

array([1, 2, 3, 4])

In [5]:
npArray = np.array(mylist)

In [6]:
type(npArray)

numpy.ndarray

In [7]:
#Creating 2D Array

matrix = [[1,2,3,4],[5,6,7,8],[10,22,33,77]]

In [8]:
np.array(matrix) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 22, 33, 77]])

#--> **Built-in Methods** to create **NumPy Arrays**

In [9]:
# np.arange(start,stop,step_size)

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
#np.zeros(shape)

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#np.ones(shape)

np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#np.linspace(start,stop,how_many_num_do_i_need)

np.linspace(0,10,3) # gives 3 evenly spaced numbers between and including 0 and 10

array([ 0.,  5., 10.])

In [18]:
#np.eye(shape)

np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#--> **Randomly** generated **NumPy Arrays**

In [21]:
#Create an array of the given shape and populate it with random samples from a "UNIFORM DISTRIBUTION" over [0,1)
# UNIFORM DISTRIBUTION: meaning all those numbers between [0,1) has the same likelihood of being picked

# np.random.rand(shape)

np.random.rand(4)

array([0.77229955, 0.83359485, 0.79254799, 0.02109723])

In [22]:
np.random.rand(4,5)

array([[0.01096524, 0.64111737, 0.15552422, 0.1157065 , 0.39345595],
       [0.37479075, 0.21345774, 0.51360581, 0.25521451, 0.77086248],
       [0.79997851, 0.57675371, 0.08696723, 0.24181   , 0.54719253],
       [0.34784404, 0.65658642, 0.76729689, 0.82452719, 0.95281646]])

In [23]:
# returns samples from the "STANDARD NORMAL DISTRIBUTION"
# np.random.randn(shape)

np.random.randn(5)

array([ 0.18610035, -1.06502774, -0.47565335, -0.5350677 , -0.32663573])

In [24]:
np.random.randn(4,5)

array([[ 2.34526711, -1.61789451, -0.82033124,  1.34840009,  0.64783535],
       [-0.66056995,  2.65423694,  0.08063298,  0.58058682, -0.92444908],
       [-0.52289008, -0.75372625,  0.13492404,  1.65947084,  0.37903878],
       [-0.11971716, -1.58760162,  0.91185691,  1.27146545, -0.20654552]])

In [27]:
# np.random.randint(start, stop, shape)

np.random.randint(0,101,5)

array([80, 61, 27, 22, 95])

In [29]:
np.random.randint(0,101,(4,5))

array([[99, 68, 96, 17, 94],
       [89, 13, 47, 39, 93],
       [49, 63, 20,  4, 83],
       [80, 30, 43, 33, 16]])

In [30]:
# Seed --> to get a particular set of random numbers

np.random.seed(42)
np.random.randint(0,101,5)

array([51, 92, 14, 71, 60])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

# Array Attributes and Methods


In [32]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

### Reshape

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

In [36]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [37]:
ranarr.max()

39

In [38]:
ranarr.argmax()

7

In [39]:
ranarr.min()

2

## Shape

Shape is an attribute that arrays have (not a method): 

In [40]:
#Vector
arr.shape

(25,)

In [43]:
#Notice the two sets of brackets
arr2 = arr.reshape(1,25)

In [44]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [45]:
arr2.shape

(1, 25)

In [46]:
arr3 = arr.reshape(25,1)

In [47]:
arr3

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [48]:
arr3.shape

(25, 1)

### dtype

In [49]:
arr.dtype

dtype('int64')

In [1]:
arrx = np.array([1.2, 3.4, 5.6])
print(arrx.dtype)

NameError: name 'np' is not defined

THE END